title: One Website To Rule Them All
description: A project showcase site.
baseurl: "" 
url: "" 

collections:
  projects:
    output: true
    permalink: /projects/:name/ 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md